# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "debian/stretch64"
    config.vm.network "public_network", type: "dhcp"
    config.vm.synced_folder "../..", "/vagrant"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "wet-server-setup-debian"
        vb.cpus = 1
        vb.memory = "1024"
    end

    config.vm.provision "shell", inline: <<-SHELL
        bash /vagrant/setup/debian/install-software.sh
        bash /vagrant/setup/debian/install-common-maps.sh
        bash /vagrant/setup/debian/integrate-systemd.sh

        usermod -aG wet vagrant
    SHELL
end
