# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "fedora/31-cloud-base"
    config.vm.box_version = "31.20191023.0"
    config.vm.network "public_network", type: "dhcp"
    config.vm.synced_folder "../..", "/vagrant"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "wet-server-setup-fedora"
        vb.cpus = 1
        vb.memory = "1024"
    end

    config.vm.provider "libvirt" do |vb|
        vb.cpus = 1
        vb.memory = "1024"
    end

    config.vm.provision "shell", inline: <<-SHELL
        bash /vagrant/setup/fedora/install-software.sh

        usermod -aG wet vagrant
    SHELL
end
